# Strumenti matematici in Python

## Operazioni fondamentali
**+** addizione, **-** sottrazione, ** \* ** moltiplicazione, ** / ** divisione

In [1]:
18 + 2, 20.0 - 2, 20.0 * 6, 20 / 3

(20, 18.0, 120.0, 6.666666666666667)

** // ** parte intera della divisione, ** % ** modulo (resto della divisione)

In [2]:
parte_intera = 20 // 3
resto = 20 % 3 

print("20 diviso 3 fa %d col resto di %d." %(parte_intera, resto))

20 diviso 3 fa 6 col resto di 2.


In [3]:
# posso scrivere anche in questo modo per generare lo stesso output
print("20 diviso 3 fa " + str(parte_intera) + " col resto di " + str(resto))

20 diviso 3 fa 6 col resto di 2


In [4]:
5 % 2

1

** \*\* ** elevamento a potenza

In [5]:
2 ** 8

256

Ricordiamo che possiamo applicare la proprietà $x^{\frac{a}{b}} = \sqrt[b]{x^{a}}$ per ottenere la radice quadrata.  
Ad esempio: $49^{\frac{1}{2}} = \sqrt{49} = 7$

In [6]:
49 ** (1/2)

7.0

Numeri complessi

In [7]:
type(50 + 10j)

complex

In [8]:
u = 50 + 10j
v = 30 + 40J

u + v

(80+50j)

## Come importare una libreria

Importare l'intera libreria: **`import nome_libreria`** 

Importare un modulo: **`from nome_libreria import nome_modulo`**  

In aggiunta possiamo usare **`as nome_abbreviazione`** per usare un'abbrezione invece del nome della libreria o modulo importato

# math

https://docs.python.org/3/library/math.html

In [9]:
import math # importiamo libreria math

math.sqrt(49) # usiamo la funzione radice quadrata in math

7.0

In [10]:
from math import sqrt # importo solo la radice 

sqrt(49)

7.0

In [11]:
from math import sqrt as rq # importo solo la radice e la richiamo nel mio condice con rq (radice quadrata)

rq(144)

12.0

In [12]:
math.factorial(6) # calcoliamo il fattoriale

720

In [13]:
6*5*4*3*2*1

720

Verifichiamo l'identità trigonometrica $\tan x = \frac{\sin x}{\cos x}$ per $x = 0, \pi$  
https://en.wikipedia.org/wiki/List_of_trigonometric_identities

In [14]:
math.pi

3.141592653589793

In [15]:
x = 0
math.tan(x) == math.sin(x) / math.cos(x)

True

In [16]:
y = math.pi
math.tan(y) == math.sin(y) / math.cos(y)

True

Verichiamo la formula di Eulero $e^{ix} = \cos x + i\sin x$, per $x = 0, \pi$

In [17]:
x = 0
math.e ** (x*1j) == math.cos(x) + math.sin(x)*1j

True

In [18]:
y = math.pi
math.e ** (y*1j) == math.cos(y) + math.sin(y)*1j

True

In [19]:
math.e ** (0*1j)

(1+0j)

## statistics

https://docs.python.org/3/library/statistics.html

In [20]:
import statistics

In [21]:
voti = [2.3,0,4,5,5,3,4,5,4.5,2,3,4,5,2]

In [22]:
statistics.mean(voti)

3.4857142857142858

In [23]:
statistics.median(voti)

4.0

In [24]:
statistics.mode(voti)

5

In [25]:
statistics.stdev(voti)

1.5047908839422188

## NumPy

Sito ufficiale http://www.numpy.org  
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In [26]:
import numpy as np # importo libreria NumPy e la richiamerò nel mio codice con 'np'

In [27]:
np.__version__ # versione di NumPy

'1.13.3'

In [28]:
np.sqrt(49)

7.0

### Vettori (NumPy array unidimensionali)

In [29]:
altezze_lista = [175, 180, 168, 190, 175, 164, 189, 173, 171.23] 
altezze_np = np.array(altezze_lista) # creriamo un NumPy array

In [30]:
altezze_lista, type(altezze_lista)

([175, 180, 168, 190, 175, 164, 189, 173, 171.23], list)

In [31]:
altezze_lista * 2

[175,
 180,
 168,
 190,
 175,
 164,
 189,
 173,
 171.23,
 175,
 180,
 168,
 190,
 175,
 164,
 189,
 173,
 171.23]

In [32]:
altezze_np, type(altezze_np)

(array([ 175.  ,  180.  ,  168.  ,  190.  ,  175.  ,  164.  ,  189.  ,
         173.  ,  171.23]), numpy.ndarray)

In [33]:
altezze2 = altezze_np * 2 # moltiplicazione di un vettore matematico (nparray) con uno scalare (2)

In [34]:
altezze2

array([ 350.  ,  360.  ,  336.  ,  380.  ,  350.  ,  328.  ,  378.  ,
        346.  ,  342.46])

In [35]:
altezze_np

array([ 175.  ,  180.  ,  168.  ,  190.  ,  175.  ,  164.  ,  189.  ,
        173.  ,  171.23])

In [36]:
altezze_np / 2

array([ 87.5  ,  90.   ,  84.   ,  95.   ,  87.5  ,  82.   ,  94.5  ,
        86.5  ,  85.615])

In [37]:
media = np.mean(altezze_np)
media

176.13666666666666

In [38]:
np.round(media)

176.0

In [39]:
mediana = np.median(altezze_np)
mediana

175.0

In [40]:
somma = np.sum(altezze_np)
somma

1585.23

In [41]:
zeri = np.zeros(10) # vettore di 10 valori 0
zeri

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [42]:
uni = np.ones(10) # vettore di 10 valori 1
uni

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
uni3 = np.append(uni,3) # aggiungo valori alla fine 
uni3

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  3.])

In [44]:
uni

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
np.insert(uni,8,2) # np.insert(np-array,indice,valore)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.])

### Matrici (NumPy array bidimensionali)

In [46]:
lista_diliste = [[1,2,3],[4,5,6],[7,8,9]]
matrice = np.array(lista_diliste)

matrice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
lista_diliste[0][1]

2

In [48]:
type(lista_diliste)

list

In [49]:
type(matrice)

numpy.ndarray

In [50]:
matrice.shape # dimensione della matrice con l'attributo .shape di np.mat

(3, 3)

In [51]:
matrice.size # numero elementi

9

In [52]:
matrice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
matrice[1][2]

6

In [54]:
sottomatrice = matrice[1:, :2] # matrice[righe selezionate, colonne slezionate]
sottomatrice

array([[4, 5],
       [7, 8]])

In [55]:
sottom = matrice[: : 2, : :2]
sottom

array([[1, 3],
       [7, 9]])

In [56]:
sottom.shape

(2, 2)

In [57]:
prima_riga = matrice[:,0:1]
prima_riga

array([[1],
       [4],
       [7]])

In [58]:
matrice_random = np.random.random((2,3)) # matrice random 3x3  
matrice_random

array([[ 0.32632093,  0.65238981,  0.8326403 ],
       [ 0.05445534,  0.99464864,  0.59364713]])

In [59]:
matrice2 = 2 * matrice_random
matrice2

array([[ 0.65264187,  1.30477961,  1.66528059],
       [ 0.10891068,  1.98929729,  1.18729426]])

In [60]:
matrice2 + matrice_random

array([[ 0.9789628 ,  1.95716942,  2.49792089],
       [ 0.16336602,  2.98394593,  1.78094139]])

La moltiplicazione fra matrici funziona nel caso di matrici di forma (a,b) * (b,a)

In [61]:
mat1 = np.mat([[1,2,3], [4,5,6]])
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [62]:
mat2 = np.mat([[0,21,3], [0,5,61]])
mat2

matrix([[ 0, 21,  3],
        [ 0,  5, 61]])

In [63]:
mat1.shape, mat2.shape

((2, 3), (2, 3))

In [64]:
# La moltiplicazione fra mat1 e mat2 darebbe quindi errore, occorre trasporre una delle due con .T
mat2t = mat2.T
mat2t

matrix([[ 0,  0],
        [21,  5],
        [ 3, 61]])

In [65]:
mat1.shape, mat2t.shape

((2, 3), (3, 2))

In [66]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [67]:
mat2t

matrix([[ 0,  0],
        [21,  5],
        [ 3, 61]])

In [68]:
# Ora le matrici sono pronte per essere moltiplicate
mat1 * mat2t

matrix([[ 51, 193],
        [123, 391]])

Nel caso che tu volessi moltiplicare singolarmente elemento per elemento fra matrici con la stessa forma di può usare **.multiply()**

In [69]:
molt_el = np.multiply(mat1, mat2)
molt_el

matrix([[  0,  42,   9],
        [  0,  25, 366]])

In [70]:
np.delete(molt_el,1,axis=0) # axis = 0 : riga, elimino la riga con indice 1

matrix([[ 0, 42,  9]])

In [71]:
np.delete(molt_el,2,axis=1) # axis = 1 : colonnam, elimino la colonna con indice 2

matrix([[ 0, 42],
        [ 0, 25]])

In [72]:
# molt_el rimane intatta, se vogliamo possiamo salvare l'output in un'altra variable
molt_el

matrix([[  0,  42,   9],
        [  0,  25, 366]])

### Altri Numpy array e un po' di algebra
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

In [73]:
# Matrice identità
id5 = np.identity(5)
id5

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [74]:
np.random.randint(10,size=(5,6)) # random integer da 0 a 9 in un NumPy array (5,6)

array([[2, 7, 3, 9, 8, 3],
       [0, 3, 7, 6, 0, 8],
       [2, 4, 0, 4, 1, 7],
       [4, 8, 1, 4, 3, 1],
       [8, 1, 4, 2, 5, 5]])

In [75]:
matrice3 = np.random.random((4,4))
matrice3

array([[ 0.9430174 ,  0.62104159,  0.45705054,  0.22768795],
       [ 0.62037741,  0.78274395,  0.00339514,  0.52609486],
       [ 0.79739345,  0.19657992,  0.32746044,  0.2080318 ],
       [ 0.8308927 ,  0.38253556,  0.86480449,  0.36659995]])

In [76]:
matrice4 = np.round(matrice3, 2)
matrice4

array([[ 0.94,  0.62,  0.46,  0.23],
       [ 0.62,  0.78,  0.  ,  0.53],
       [ 0.8 ,  0.2 ,  0.33,  0.21],
       [ 0.83,  0.38,  0.86,  0.37]])

In [77]:
# Diagonale della matrice
matrice4.diagonal()

array([ 0.94,  0.78,  0.33,  0.37])

Determinante
https://it.wikipedia.org/wiki/Determinante

In [78]:
# Deteminante della matrice (matrice quadrata)
np.linalg.det(matrice4)

-0.077293279999999978

Autovalori
https://it.wikipedia.org/wiki/Autovettore_e_autovalore

In [79]:
# Autovalori della matrice
np.linalg.eig(matrice4)

(array([ 2.06548621+0.j        , -0.24780295+0.j        ,
         0.30115837+0.24559348j,  0.30115837-0.24559348j]),
 array([[-0.54171990+0.j        , -0.36351669+0.j        ,
         -0.17598652+0.17860119j, -0.17598652-0.17860119j],
        [-0.49481822+0.j        ,  0.51201083+0.j        ,
         -0.35677734-0.4142391j , -0.35677734+0.4142391j ],
        [-0.37527981+0.j        ,  0.53239984+0.j        ,
          0.26984543+0.21632441j,  0.26984543-0.21632441j],
        [-0.56644464+0.j        , -0.56767150+0.j        ,
          0.72016210+0.j        ,  0.72016210-0.j        ]]))